# Generated by Django 4.2.2 on 2023-06-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0003_delete_notification_rename_user_rating_vendor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
