# Generated by Django 4.2.2 on 2023-06-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_remove_comment_review_comment_review_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderation',
            old_name='review',
            new_name='review_id',
        ),
        migrations.RenameField(
            model_name='moderation',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='review',
            new_name='review_id',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='user_id',
        ),
    ]
