# Generated by Django 4.2.2 on 2023-06-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0006_rename_review_moderation_review_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderation',
            name='review_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='review_id',
            field=models.IntegerField(),
        ),
    ]
